/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.*;
import java.util.ArrayList;

/**
 *
 * @author Youssef
 */
public class Casablanca extends javax.swing.JFrame
{

    /**
     * Creates new form Casablanca
     */
    Controller con;
    DateValidator dv;

    public Casablanca()
    {
        initComponents();
        con = Controller.getInstance();
        dv = new DateValidator();
        fillChooseCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        CHOOSEDATE = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CHOOSEDATEENDDATE = new javax.swing.JTextField();
        CHOOSEDATESTARTDATE = new javax.swing.JTextField();
        CHOOSEDATEBACKBUTTON = new javax.swing.JButton();
        CHOOSEDATESEARCHBUTTON = new javax.swing.JButton();
        CHOOSEDATECOMBOBOX = new javax.swing.JComboBox();
        CHOOSEDATEDATEFORMAT = new javax.swing.JLabel();
        CHOOSEDATEDATEFORMAT2 = new javax.swing.JLabel();
        CHOOSEDATEFEEDBACKLABEL = new javax.swing.JLabel();
        SHOWAVAILABLEROOMS = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        AVAILABLEROOMSBOOKBUTTON = new javax.swing.JButton();
        AVAILABLEROOMSBACKBUTTON = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        SHOWAVAILABLELIST = new javax.swing.JList();
        CREATEUSERPANEL = new javax.swing.JPanel();
        LABEL1 = new javax.swing.JLabel();
        CREATEUSERFULLNAME = new javax.swing.JTextField();
        CREATEUSERGENERATEBUTTON = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CREATEUSERUSERNAME = new javax.swing.JTextField();
        CREATEUSERPASSWORD = new javax.swing.JTextField();
        CREATEUSERSAVEUSER = new javax.swing.JButton();
        CREATEUSERBACKBUTTON = new javax.swing.JButton();
        LOGIN = new javax.swing.JPanel();
        USERNAME = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LOGINBUTTON = new javax.swing.JButton();
        GETFEEDBACK = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CREATEUSERBUTTON = new javax.swing.JButton();
        WELCOME = new javax.swing.JPanel();
        LOGOUT = new javax.swing.JButton();
        BOOKROOMBUTTON = new javax.swing.JButton();
        STANDBYBUTTON = new javax.swing.JButton();
        SHOWBOOKEDBUTTON = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        SHOWBOOKEDROOMS = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DELETERESERVATION = new javax.swing.JButton();
        SHOWREGINFOBUTTON = new javax.swing.JButton();
        BACKBUTTONBOOKEDROOMS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SHOWBOOKEDROOMSTEXTAREA = new javax.swing.JTextArea();
        SHOWREGINFO = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        REGINFOFIRSTNAME = new javax.swing.JTextField();
        REGINFOADRESS = new javax.swing.JTextField();
        REGINFOTRAVELAGENCY = new javax.swing.JTextField();
        REGINFOPHONE = new javax.swing.JTextField();
        REGINFOCHECKINDATE = new javax.swing.JTextField();
        REGINFONUMBERNIGHTS = new javax.swing.JTextField();
        REGINFOROOMSIZE = new javax.swing.JTextField();
        REGINFOROOMNUMBER = new javax.swing.JTextField();
        REGINFOLASTNAME = new javax.swing.JTextField();
        REGINFOCOUNTRY = new javax.swing.JTextField();
        REGINFOEMAIL = new javax.swing.JTextField();
        REGINFOPASSWORD = new javax.swing.JTextField();
        REGINFOURSERNAME = new javax.swing.JTextField();
        REGINFOBACKBUTTON = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        BOOKROOM = new javax.swing.JPanel();
        BOOKROOMFIRSTNAME = new javax.swing.JTextField();
        BOOKROOMPHONE = new javax.swing.JTextField();
        BOOKROOMADRESS = new javax.swing.JTextField();
        BOOKROOMTRAVELAGENCY = new javax.swing.JTextField();
        BOOKROOMCHECKINDATE = new javax.swing.JTextField();
        BOOKROOMNUMBEROFNIGHTS = new javax.swing.JTextField();
        BOOKROOMROOMNUMBER = new javax.swing.JTextField();
        BOOKROOMCOUNTRY = new javax.swing.JTextField();
        BOOKROOMEMAIL = new javax.swing.JTextField();
        BOOKROOMLASTNAME = new javax.swing.JTextField();
        BOOKROOMROOMSIZE = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        BOOKROOMCANCELBUTTON = new javax.swing.JButton();
        BOOKROOMCONFIRMBUTTON = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        FROMROOMNUMBER = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        FROMROOMSIZE = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        SHOWSTANDBYROOMS = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        STANDBYROOMTEXTAREA = new javax.swing.JTextArea();
        STANDBYROOMBACKBUTTON = new javax.swing.JButton();
        STANDBYROOMDECLINEBUTTON = new javax.swing.JButton();
        STANDBYROOMACCEPTBUTTON = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel6.setText("START DATE");

        jLabel7.setText("END DATE");

        jLabel8.setText("ROOM SIZE");

        CHOOSEDATESTARTDATE.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CHOOSEDATESTARTDATEActionPerformed(evt);
            }
        });

        CHOOSEDATEBACKBUTTON.setText("BACK");

        CHOOSEDATESEARCHBUTTON.setText("SEARCH");
        CHOOSEDATESEARCHBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CHOOSEDATESEARCHBUTTONActionPerformed(evt);
            }
        });

        CHOOSEDATECOMBOBOX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CHOOSEDATEDATEFORMAT.setText("DD-MM-YY");

        CHOOSEDATEDATEFORMAT2.setText("DD-MM-YY");

        javax.swing.GroupLayout CHOOSEDATELayout = new javax.swing.GroupLayout(CHOOSEDATE);
        CHOOSEDATE.setLayout(CHOOSEDATELayout);
        CHOOSEDATELayout.setHorizontalGroup(
            CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CHOOSEDATELayout.createSequentialGroup()
                .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CHOOSEDATELayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CHOOSEDATELayout.createSequentialGroup()
                                .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(49, 49, 49)
                                .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CHOOSEDATESTARTDATE)
                                    .addComponent(CHOOSEDATEENDDATE, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(CHOOSEDATECOMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CHOOSEDATEDATEFORMAT)
                                    .addComponent(CHOOSEDATEDATEFORMAT2)))
                            .addComponent(CHOOSEDATEFEEDBACKLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CHOOSEDATELayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(CHOOSEDATEBACKBUTTON)
                        .addGap(101, 101, 101)
                        .addComponent(CHOOSEDATESEARCHBUTTON)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        CHOOSEDATELayout.setVerticalGroup(
            CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CHOOSEDATELayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHOOSEDATESTARTDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(CHOOSEDATEDATEFORMAT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHOOSEDATEENDDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CHOOSEDATEDATEFORMAT2))
                .addGap(43, 43, 43)
                .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CHOOSEDATECOMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHOOSEDATEBACKBUTTON)
                    .addComponent(CHOOSEDATESEARCHBUTTON))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(CHOOSEDATEFEEDBACKLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(CHOOSEDATE, "card4");

        jLabel16.setText("ROOM#");

        jLabel17.setText("ROOM SIZE");

        jLabel18.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        jLabel18.setText("SHOW AVAILABLE ROOMS");

        AVAILABLEROOMSBOOKBUTTON.setText("BOOK");
        AVAILABLEROOMSBOOKBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AVAILABLEROOMSBOOKBUTTONActionPerformed(evt);
            }
        });

        AVAILABLEROOMSBACKBUTTON.setText("BACK");
        AVAILABLEROOMSBACKBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AVAILABLEROOMSBACKBUTTONActionPerformed(evt);
            }
        });

        SHOWAVAILABLELIST.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(SHOWAVAILABLELIST);

        javax.swing.GroupLayout SHOWAVAILABLEROOMSLayout = new javax.swing.GroupLayout(SHOWAVAILABLEROOMS);
        SHOWAVAILABLEROOMS.setLayout(SHOWAVAILABLEROOMSLayout);
        SHOWAVAILABLEROOMSLayout.setHorizontalGroup(
            SHOWAVAILABLEROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWAVAILABLEROOMSLayout.createSequentialGroup()
                .addGroup(SHOWAVAILABLEROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SHOWAVAILABLEROOMSLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(SHOWAVAILABLEROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SHOWAVAILABLEROOMSLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(88, 88, 88)
                                .addComponent(jLabel17))
                            .addComponent(jScrollPane2))
                        .addGap(81, 81, 81)
                        .addGroup(SHOWAVAILABLEROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AVAILABLEROOMSBOOKBUTTON)
                            .addComponent(AVAILABLEROOMSBACKBUTTON)))
                    .addGroup(SHOWAVAILABLEROOMSLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel18)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        SHOWAVAILABLEROOMSLayout.setVerticalGroup(
            SHOWAVAILABLEROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWAVAILABLEROOMSLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(SHOWAVAILABLEROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SHOWAVAILABLEROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SHOWAVAILABLEROOMSLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AVAILABLEROOMSBOOKBUTTON)
                        .addGap(18, 18, 18)
                        .addComponent(AVAILABLEROOMSBACKBUTTON))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );

        getContentPane().add(SHOWAVAILABLEROOMS, "card7");

        LABEL1.setText("FULL NAME");

        CREATEUSERFULLNAME.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CREATEUSERFULLNAMEActionPerformed(evt);
            }
        });

        CREATEUSERGENERATEBUTTON.setText("GENERATE ");
        CREATEUSERGENERATEBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CREATEUSERGENERATEBUTTONActionPerformed(evt);
            }
        });

        jLabel13.setText("USERNAME");

        jLabel14.setText("PASSWORD");

        CREATEUSERUSERNAME.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CREATEUSERUSERNAMEActionPerformed(evt);
            }
        });

        CREATEUSERPASSWORD.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CREATEUSERPASSWORDActionPerformed(evt);
            }
        });

        CREATEUSERSAVEUSER.setText("SAVE USER");

        CREATEUSERBACKBUTTON.setText("BACK");
        CREATEUSERBACKBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CREATEUSERBACKBUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CREATEUSERPANELLayout = new javax.swing.GroupLayout(CREATEUSERPANEL);
        CREATEUSERPANEL.setLayout(CREATEUSERPANELLayout);
        CREATEUSERPANELLayout.setHorizontalGroup(
            CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CREATEUSERPANELLayout.createSequentialGroup()
                .addGroup(CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(CREATEUSERPANELLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CREATEUSERPANELLayout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(LABEL1))))
                .addGap(18, 18, 18)
                .addGroup(CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CREATEUSERGENERATEBUTTON)
                    .addComponent(CREATEUSERFULLNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(CREATEUSERUSERNAME)
                    .addComponent(CREATEUSERPASSWORD))
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CREATEUSERPANELLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CREATEUSERSAVEUSER, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(CREATEUSERBACKBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86))
        );
        CREATEUSERPANELLayout.setVerticalGroup(
            CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CREATEUSERPANELLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL1)
                    .addComponent(CREATEUSERFULLNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CREATEUSERGENERATEBUTTON)
                .addGap(18, 18, 18)
                .addGroup(CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CREATEUSERUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(29, 29, 29)
                .addGroup(CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CREATEUSERPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(CREATEUSERSAVEUSER)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CREATEUSERBACKBUTTON)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(CREATEUSERPANEL, "card10");

        USERNAME.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                USERNAMEActionPerformed(evt);
            }
        });

        jLabel2.setText("PASSWORD");

        LOGINBUTTON.setText("LOG IN");

        GETFEEDBACK.setText("GET FEEDBACK");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        jLabel4.setText("PLEASE LOGIN  AS A STAFF");

        jLabel1.setText("USERNAME");

        CREATEUSERBUTTON.setText("CREATE USER");

        javax.swing.GroupLayout LOGINLayout = new javax.swing.GroupLayout(LOGIN);
        LOGIN.setLayout(LOGINLayout);
        LOGINLayout.setHorizontalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GETFEEDBACK)
                    .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGINLayout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGINLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGINLayout.createSequentialGroup()
                        .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CREATEUSERBUTTON)
                            .addComponent(LOGINBUTTON))
                        .addGap(48, 48, 48))))
        );
        LOGINLayout.setVerticalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CREATEUSERBUTTON))
                .addGap(26, 26, 26)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(GETFEEDBACK)
                .addGap(18, 18, 18)
                .addComponent(LOGINBUTTON)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        getContentPane().add(LOGIN, "card2");

        LOGOUT.setText("LOG OUT");

        BOOKROOMBUTTON.setText("BOOK ROOM");

        STANDBYBUTTON.setText("SHOW STANDBY ROOMS");

        SHOWBOOKEDBUTTON.setText("SHOW BOOKED ROOMS");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        jLabel5.setText("WELCOME TO CASABLANCA HOTEL RESERVATION");

        javax.swing.GroupLayout WELCOMELayout = new javax.swing.GroupLayout(WELCOME);
        WELCOME.setLayout(WELCOMELayout);
        WELCOMELayout.setHorizontalGroup(
            WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WELCOMELayout.createSequentialGroup()
                .addGroup(WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WELCOMELayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(WELCOMELayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(STANDBYBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SHOWBOOKEDBUTTON)
                            .addComponent(BOOKROOMBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WELCOMELayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LOGOUT)
                .addGap(25, 25, 25))
        );
        WELCOMELayout.setVerticalGroup(
            WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WELCOMELayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(SHOWBOOKEDBUTTON)
                .addGap(18, 18, 18)
                .addComponent(STANDBYBUTTON)
                .addGap(18, 18, 18)
                .addComponent(BOOKROOMBUTTON)
                .addGap(51, 51, 51)
                .addComponent(LOGOUT)
                .addGap(47, 47, 47))
        );

        getContentPane().add(WELCOME, "card3");

        jLabel9.setText("ROOM#");

        jLabel10.setText("START DATE");

        jLabel11.setText("END DATE");

        DELETERESERVATION.setText("DELETE RESERVATION");
        DELETERESERVATION.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DELETERESERVATIONActionPerformed(evt);
            }
        });

        SHOWREGINFOBUTTON.setText("SHOW REGISTRAION INFO");
        SHOWREGINFOBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SHOWREGINFOBUTTONActionPerformed(evt);
            }
        });

        BACKBUTTONBOOKEDROOMS.setText("BACK");

        SHOWBOOKEDROOMSTEXTAREA.setColumns(20);
        SHOWBOOKEDROOMSTEXTAREA.setRows(5);
        jScrollPane1.setViewportView(SHOWBOOKEDROOMSTEXTAREA);

        javax.swing.GroupLayout SHOWBOOKEDROOMSLayout = new javax.swing.GroupLayout(SHOWBOOKEDROOMS);
        SHOWBOOKEDROOMS.setLayout(SHOWBOOKEDROOMSLayout);
        SHOWBOOKEDROOMSLayout.setHorizontalGroup(
            SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWBOOKEDROOMSLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
            .addGroup(SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SHOWBOOKEDROOMSLayout.createSequentialGroup()
                    .addGroup(SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SHOWBOOKEDROOMSLayout.createSequentialGroup()
                            .addGap(263, 263, 263)
                            .addGroup(SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SHOWREGINFOBUTTON)
                                    .addComponent(DELETERESERVATION, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(BACKBUTTONBOOKEDROOMS)))
                        .addGroup(SHOWBOOKEDROOMSLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel9)
                            .addGap(21, 21, 21)
                            .addComponent(jLabel10)
                            .addGap(33, 33, 33)
                            .addComponent(jLabel11)))
                    .addContainerGap(155, Short.MAX_VALUE)))
        );
        SHOWBOOKEDROOMSLayout.setVerticalGroup(
            SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWBOOKEDROOMSLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SHOWBOOKEDROOMSLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11))
                    .addGap(18, 18, 18)
                    .addComponent(DELETERESERVATION)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(SHOWREGINFOBUTTON)
                    .addGap(148, 148, 148)
                    .addComponent(BACKBUTTONBOOKEDROOMS)
                    .addContainerGap(156, Short.MAX_VALUE)))
        );

        getContentPane().add(SHOWBOOKEDROOMS, "card5");

        jLabel34.setText("FIRST NAME(S)");

        jLabel35.setText("ADRESS");

        jLabel36.setText("PHONE");

        jLabel37.setText("TRAVEL AGENCY");

        jLabel38.setText("CHECK IN(DAY/MONTH)");

        jLabel39.setText("# OF NIGHTS(S)");

        jLabel40.setText("ROOM SIZE");

        jLabel41.setText("ROOM#");

        jLabel42.setText("LAST NAME");

        jLabel43.setText("COUNTRY");

        jLabel44.setText("EMAIL");

        jLabel46.setText("USERNAME");

        jLabel47.setText("PASSWORD");

        REGINFOFIRSTNAME.setEditable(false);
        REGINFOFIRSTNAME.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                REGINFOFIRSTNAMEActionPerformed(evt);
            }
        });

        REGINFOADRESS.setEditable(false);

        REGINFOTRAVELAGENCY.setEditable(false);

        REGINFOPHONE.setEditable(false);

        REGINFOCHECKINDATE.setEditable(false);

        REGINFONUMBERNIGHTS.setEditable(false);

        REGINFOROOMSIZE.setEditable(false);

        REGINFOROOMNUMBER.setEditable(false);

        REGINFOLASTNAME.setEditable(false);

        REGINFOCOUNTRY.setEditable(false);

        REGINFOEMAIL.setEditable(false);

        REGINFOPASSWORD.setEditable(false);

        REGINFOURSERNAME.setEditable(false);

        REGINFOBACKBUTTON.setText("BACK");

        jLabel48.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        jLabel48.setText("REGISTRATION INFORMATION");

        javax.swing.GroupLayout SHOWREGINFOLayout = new javax.swing.GroupLayout(SHOWREGINFO);
        SHOWREGINFO.setLayout(SHOWREGINFOLayout);
        SHOWREGINFOLayout.setHorizontalGroup(
            SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel39)
                            .addComponent(jLabel38)
                            .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel37)
                                .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                                .addComponent(REGINFOROOMSIZE, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(REGINFOBACKBUTTON))
                                    .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                                                .addComponent(REGINFOFIRSTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel41))
                                            .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                                                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(REGINFOPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(REGINFOADRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(REGINFOTRAVELAGENCY, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(REGINFOCHECKINDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(REGINFONUMBERNIGHTS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel42)
                                                    .addComponent(jLabel43)
                                                    .addComponent(jLabel44)
                                                    .addComponent(jLabel46)
                                                    .addComponent(jLabel47))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(REGINFOROOMNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(REGINFOLASTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(REGINFOCOUNTRY, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(REGINFOEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(REGINFOPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(REGINFOURSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(101, Short.MAX_VALUE))))
                    .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel48)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        SHOWREGINFOLayout.setVerticalGroup(
            SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel48)
                .addGap(34, 34, 34)
                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jLabel41)
                            .addComponent(REGINFOFIRSTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(REGINFOROOMNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(jLabel42)
                            .addComponent(REGINFOADRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(REGINFOLASTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(jLabel43)
                            .addComponent(REGINFOPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(REGINFOCOUNTRY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(jLabel44)
                            .addComponent(REGINFOTRAVELAGENCY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(REGINFOEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(jLabel46)
                            .addComponent(REGINFOCHECKINDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(REGINFOURSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel47)
                                .addComponent(REGINFOPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel39)))
                    .addComponent(REGINFONUMBERNIGHTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(REGINFOROOMSIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(REGINFOBACKBUTTON)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(SHOWREGINFO, "card9");

        BOOKROOMFIRSTNAME.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BOOKROOMFIRSTNAMEActionPerformed(evt);
            }
        });

        jLabel19.setText("FIRST NAME(S)");

        jLabel20.setText("ADRESS");

        jLabel21.setText("PHONE");

        jLabel22.setText("TRAVEL AGENCY");

        jLabel24.setText("CHECK IN(DAY/MONTH)");

        jLabel25.setText("# OF NIGHTS(S)");

        jLabel26.setText("ROOM SIZE");

        jLabel27.setText("ROOM#");

        jLabel28.setText("LAST NAME");

        jLabel29.setText("COUNTRY");

        jLabel30.setText("EMAIL");

        BOOKROOMCANCELBUTTON.setText("CANCEL");

        BOOKROOMCONFIRMBUTTON.setText("CONFIRM");

        jLabel31.setText("ROOM#");

        FROMROOMNUMBER.setEditable(false);

        jLabel32.setText("ROOMSIZE");

        FROMROOMSIZE.setEditable(false);

        jLabel33.setText("REG INFO.");

        javax.swing.GroupLayout BOOKROOMLayout = new javax.swing.GroupLayout(BOOKROOM);
        BOOKROOM.setLayout(BOOKROOMLayout);
        BOOKROOMLayout.setHorizontalGroup(
            BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BOOKROOMLayout.createSequentialGroup()
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BOOKROOMLayout.createSequentialGroup()
                        .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BOOKROOMLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(BOOKROOMLayout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addGap(10, 10, 10)
                                            .addComponent(BOOKROOMTRAVELAGENCY, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(BOOKROOMLayout.createSequentialGroup()
                                            .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 79, Short.MAX_VALUE))
                                            .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(BOOKROOMLayout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(BOOKROOMADRESS, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                                                .addGroup(BOOKROOMLayout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(BOOKROOMPHONE))
                                                .addGroup(BOOKROOMLayout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(BOOKROOMFIRSTNAME))))
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BOOKROOMLayout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(18, 18, 18)
                                        .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BOOKROOMLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel23))
                                            .addGroup(BOOKROOMLayout.createSequentialGroup()
                                                .addComponent(BOOKROOMCHECKINDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(BOOKROOMLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(BOOKROOMLayout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BOOKROOMROOMSIZE, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BOOKROOMLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BOOKROOMNUMBEROFNIGHTS, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(9, 9, 9)
                        .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BOOKROOMLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BOOKROOMLASTNAME))
                            .addGroup(BOOKROOMLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(BOOKROOMROOMNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BOOKROOMLayout.createSequentialGroup()
                                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BOOKROOMCOUNTRY)
                                    .addComponent(BOOKROOMEMAIL)))))
                    .addGroup(BOOKROOMLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(FROMROOMNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FROMROOMSIZE, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BOOKROOMLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BOOKROOMCANCELBUTTON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BOOKROOMCONFIRMBUTTON)
                .addGap(23, 23, 23))
        );
        BOOKROOMLayout.setVerticalGroup(
            BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BOOKROOMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(jLabel33))
                    .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FROMROOMNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)
                        .addComponent(FROMROOMSIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOOKROOMROOMNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(BOOKROOMFIRSTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(BOOKROOMADRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(BOOKROOMLASTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(BOOKROOMPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(BOOKROOMCOUNTRY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(BOOKROOMTRAVELAGENCY, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(BOOKROOMEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(BOOKROOMCHECKINDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(6, 6, 6)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(BOOKROOMNUMBEROFNIGHTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(BOOKROOMROOMSIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOOKROOMCANCELBUTTON)
                    .addComponent(BOOKROOMCONFIRMBUTTON))
                .addGap(44, 44, 44))
        );

        getContentPane().add(BOOKROOM, "card8");

        STANDBYROOMTEXTAREA.setColumns(20);
        STANDBYROOMTEXTAREA.setRows(5);
        jScrollPane5.setViewportView(STANDBYROOMTEXTAREA);

        STANDBYROOMBACKBUTTON.setText("BACK");

        STANDBYROOMDECLINEBUTTON.setText("DECLINE");

        STANDBYROOMACCEPTBUTTON.setText("ACCEPT");

        jLabel59.setText("DAYS REMAIN");

        jLabel58.setText("END DATE");

        jLabel57.setText("START DATE");

        jLabel56.setText("ROOM#");

        javax.swing.GroupLayout SHOWSTANDBYROOMSLayout = new javax.swing.GroupLayout(SHOWSTANDBYROOMS);
        SHOWSTANDBYROOMS.setLayout(SHOWSTANDBYROOMSLayout);
        SHOWSTANDBYROOMSLayout.setHorizontalGroup(
            SHOWSTANDBYROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWSTANDBYROOMSLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(SHOWSTANDBYROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SHOWSTANDBYROOMSLayout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel57)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel59))
                    .addComponent(jScrollPane5))
                .addGap(28, 28, 28)
                .addGroup(SHOWSTANDBYROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(STANDBYROOMACCEPTBUTTON)
                    .addComponent(STANDBYROOMDECLINEBUTTON))
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SHOWSTANDBYROOMSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(STANDBYROOMBACKBUTTON)
                .addGap(20, 20, 20))
        );
        SHOWSTANDBYROOMSLayout.setVerticalGroup(
            SHOWSTANDBYROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWSTANDBYROOMSLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(SHOWSTANDBYROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(jLabel57)
                    .addComponent(jLabel58)
                    .addComponent(jLabel59))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SHOWSTANDBYROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SHOWSTANDBYROOMSLayout.createSequentialGroup()
                        .addComponent(STANDBYROOMACCEPTBUTTON)
                        .addGap(14, 14, 14)
                        .addComponent(STANDBYROOMDECLINEBUTTON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(STANDBYROOMBACKBUTTON)
                        .addGap(36, 36, 36))
                    .addGroup(SHOWSTANDBYROOMSLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(139, Short.MAX_VALUE))))
        );

        getContentPane().add(SHOWSTANDBYROOMS, "card6");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void USERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERNAMEActionPerformed

    private void CHOOSEDATESTARTDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHOOSEDATESTARTDATEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHOOSEDATESTARTDATEActionPerformed

    private void DELETERESERVATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETERESERVATIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DELETERESERVATIONActionPerformed

    private void SHOWREGINFOBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWREGINFOBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SHOWREGINFOBUTTONActionPerformed

    private void REGINFOFIRSTNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGINFOFIRSTNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGINFOFIRSTNAMEActionPerformed

    private void BOOKROOMFIRSTNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOKROOMFIRSTNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOOKROOMFIRSTNAMEActionPerformed

    private void CHOOSEDATESEARCHBUTTONActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CHOOSEDATESEARCHBUTTONActionPerformed
    {//GEN-HEADEREND:event_CHOOSEDATESEARCHBUTTONActionPerformed
        // my boookk button = search
        ArrayList<Room> rooms = new ArrayList();
        String sDate = CHOOSEDATESTARTDATE.getText();
        String eDate = CHOOSEDATEENDDATE.getText();
        String dateFormat = "dd-MM-yy";

        if (dv.isDateValid(sDate, dateFormat) && dv.isDateValid(eDate, dateFormat))
        {
            
            if (CHOOSEDATECOMBOBOX.getSelectedItem().toString().equals("All"))
            {
                rooms = con.getAllFreeRooms(sDate, eDate);
            } else
            {
                int rSize = Integer.parseInt(CHOOSEDATECOMBOBOX.getSelectedItem().toString());
                rooms = con.getSizeFreeRooms(sDate, eDate, rSize);
            }
            if (!rooms.isEmpty())
            {
                fillAvailList(rooms);
                CHOOSEDATE.setVisible(false);
                SHOWAVAILABLEROOMS.setVisible(true);
            } else
            {
                CHOOSEDATEFEEDBACKLABEL.setText("No available apartments!");
            }

        }else
        {
            CHOOSEDATEFEEDBACKLABEL.setText("Please enter a valid date.");
        }
    }//GEN-LAST:event_CHOOSEDATESEARCHBUTTONActionPerformed

    private void AVAILABLEROOMSBACKBUTTONActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AVAILABLEROOMSBACKBUTTONActionPerformed
    {//GEN-HEADEREND:event_AVAILABLEROOMSBACKBUTTONActionPerformed
        SHOWAVAILABLEROOMS.setVisible(false);
        CHOOSEDATE.setVisible(true);

    }//GEN-LAST:event_AVAILABLEROOMSBACKBUTTONActionPerformed

    private void AVAILABLEROOMSBOOKBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVAILABLEROOMSBOOKBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AVAILABLEROOMSBOOKBUTTONActionPerformed

    private void CREATEUSERUSERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEUSERUSERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CREATEUSERUSERNAMEActionPerformed

    private void CREATEUSERPASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEUSERPASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CREATEUSERPASSWORDActionPerformed

    private void CREATEUSERBACKBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEUSERBACKBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CREATEUSERBACKBUTTONActionPerformed

    private void CREATEUSERGENERATEBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEUSERGENERATEBUTTONActionPerformed

        String fullName = CREATEUSERFULLNAME.getText();
        CreateUserStaff cus = new CreateUserStaff(fullName);
        CREATEUSERUSERNAME.setText(cus.getuserName());
        CREATEUSERPASSWORD.setText(cus.getPassword());
    }//GEN-LAST:event_CREATEUSERGENERATEBUTTONActionPerformed

    private void CREATEUSERFULLNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEUSERFULLNAMEActionPerformed


    }//GEN-LAST:event_CREATEUSERFULLNAMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Casablanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Casablanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Casablanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Casablanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Casablanca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AVAILABLEROOMSBACKBUTTON;
    private javax.swing.JButton AVAILABLEROOMSBOOKBUTTON;
    private javax.swing.JButton BACKBUTTONBOOKEDROOMS;
    private javax.swing.JPanel BOOKROOM;
    private javax.swing.JTextField BOOKROOMADRESS;
    private javax.swing.JButton BOOKROOMBUTTON;
    private javax.swing.JButton BOOKROOMCANCELBUTTON;
    private javax.swing.JTextField BOOKROOMCHECKINDATE;
    private javax.swing.JButton BOOKROOMCONFIRMBUTTON;
    private javax.swing.JTextField BOOKROOMCOUNTRY;
    private javax.swing.JTextField BOOKROOMEMAIL;
    private javax.swing.JTextField BOOKROOMFIRSTNAME;
    private javax.swing.JTextField BOOKROOMLASTNAME;
    private javax.swing.JTextField BOOKROOMNUMBEROFNIGHTS;
    private javax.swing.JTextField BOOKROOMPHONE;
    private javax.swing.JTextField BOOKROOMROOMNUMBER;
    private javax.swing.JTextField BOOKROOMROOMSIZE;
    private javax.swing.JTextField BOOKROOMTRAVELAGENCY;
    private javax.swing.JPanel CHOOSEDATE;
    private javax.swing.JButton CHOOSEDATEBACKBUTTON;
    private javax.swing.JComboBox CHOOSEDATECOMBOBOX;
    private javax.swing.JLabel CHOOSEDATEDATEFORMAT;
    private javax.swing.JLabel CHOOSEDATEDATEFORMAT2;
    private javax.swing.JTextField CHOOSEDATEENDDATE;
    private javax.swing.JLabel CHOOSEDATEFEEDBACKLABEL;
    private javax.swing.JButton CHOOSEDATESEARCHBUTTON;
    private javax.swing.JTextField CHOOSEDATESTARTDATE;
    private javax.swing.JButton CREATEUSERBACKBUTTON;
    private javax.swing.JButton CREATEUSERBUTTON;
    private javax.swing.JTextField CREATEUSERFULLNAME;
    private javax.swing.JButton CREATEUSERGENERATEBUTTON;
    private javax.swing.JPanel CREATEUSERPANEL;
    private javax.swing.JTextField CREATEUSERPASSWORD;
    private javax.swing.JButton CREATEUSERSAVEUSER;
    private javax.swing.JTextField CREATEUSERUSERNAME;
    private javax.swing.JButton DELETERESERVATION;
    private javax.swing.JTextField FROMROOMNUMBER;
    private javax.swing.JTextField FROMROOMSIZE;
    private javax.swing.JLabel GETFEEDBACK;
    private javax.swing.JLabel LABEL1;
    private javax.swing.JPanel LOGIN;
    private javax.swing.JButton LOGINBUTTON;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JTextField PASSWORD;
    private javax.swing.JTextField REGINFOADRESS;
    private javax.swing.JButton REGINFOBACKBUTTON;
    private javax.swing.JTextField REGINFOCHECKINDATE;
    private javax.swing.JTextField REGINFOCOUNTRY;
    private javax.swing.JTextField REGINFOEMAIL;
    private javax.swing.JTextField REGINFOFIRSTNAME;
    private javax.swing.JTextField REGINFOLASTNAME;
    private javax.swing.JTextField REGINFONUMBERNIGHTS;
    private javax.swing.JTextField REGINFOPASSWORD;
    private javax.swing.JTextField REGINFOPHONE;
    private javax.swing.JTextField REGINFOROOMNUMBER;
    private javax.swing.JTextField REGINFOROOMSIZE;
    private javax.swing.JTextField REGINFOTRAVELAGENCY;
    private javax.swing.JTextField REGINFOURSERNAME;
    private javax.swing.JList SHOWAVAILABLELIST;
    private javax.swing.JPanel SHOWAVAILABLEROOMS;
    private javax.swing.JButton SHOWBOOKEDBUTTON;
    private javax.swing.JPanel SHOWBOOKEDROOMS;
    private javax.swing.JTextArea SHOWBOOKEDROOMSTEXTAREA;
    private javax.swing.JPanel SHOWREGINFO;
    private javax.swing.JButton SHOWREGINFOBUTTON;
    private javax.swing.JPanel SHOWSTANDBYROOMS;
    private javax.swing.JButton STANDBYBUTTON;
    private javax.swing.JButton STANDBYROOMACCEPTBUTTON;
    private javax.swing.JButton STANDBYROOMBACKBUTTON;
    private javax.swing.JButton STANDBYROOMDECLINEBUTTON;
    private javax.swing.JTextArea STANDBYROOMTEXTAREA;
    private javax.swing.JTextField USERNAME;
    private javax.swing.JPanel WELCOME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables

    private void fillChooseCombo()
    {
        CHOOSEDATECOMBOBOX.removeAllItems();
        CHOOSEDATECOMBOBOX.addItem("1");
        CHOOSEDATECOMBOBOX.addItem("2");
        CHOOSEDATECOMBOBOX.addItem("5");
        CHOOSEDATECOMBOBOX.addItem("All");
    }

    private void fillAvailList(ArrayList<Room> rooms)
    {
        SHOWAVAILABLELIST.removeAll();
        Object[] o = rooms.toArray(new Object[0]);
        SHOWAVAILABLELIST.setListData(o);

    }
}
