/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.*;
import java.util.ArrayList;

/**
 *
 * @author Youssef
 */
public class Casablanca extends javax.swing.JFrame
{

    /**
     * Creates new form Casablanca
     */
    Controller con;
    DateValidator dv;

    public Casablanca()
    {
        initComponents();
        con = Controller.getInstance();
        dv = new DateValidator();
        fillChooseCombo();
        showMenuHideOthers();
        setTitle("Casablanca administration system");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        WELCOME = new javax.swing.JPanel();
        LOGOUT = new javax.swing.JButton();
        BOOKROOMBUTTON = new javax.swing.JButton();
        STANDBYBUTTON = new javax.swing.JButton();
        SHOWBOOKEDBUTTON = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CHOOSEDATE = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CHOOSEDATEENDDATE = new javax.swing.JTextField();
        CHOOSEDATESTARTDATE = new javax.swing.JTextField();
        CHOOSEDATEBACKBUTTON = new javax.swing.JButton();
        CHOOSEDATESEARCHBUTTON = new javax.swing.JButton();
        CHOOSEDATECOMBOBOX = new javax.swing.JComboBox();
        CHOOSEDATEDATEFORMAT = new javax.swing.JLabel();
        CHOOSEDATEDATEFORMAT2 = new javax.swing.JLabel();
        CHOOSEDATEFEEDBACKLABEL = new javax.swing.JLabel();
        SHOWAVAILABLEROOMS = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        AVAILABLEROOMSBOOKBUTTON = new javax.swing.JButton();
        AVAILABLEROOMSBACKBUTTON = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        SHOWAVAILABLELIST = new javax.swing.JList();
        BOOKROOM = new javax.swing.JPanel();
        BOOKROOMFIRSTNAME = new javax.swing.JTextField();
        BOOKROOMPHONE = new javax.swing.JTextField();
        BOOKROOMADRESS = new javax.swing.JTextField();
        BOOKROOMTRAVELAGENCY = new javax.swing.JTextField();
        BOOKROOMROOMNUMBER = new javax.swing.JTextField();
        BOOKROOMCOUNTRY = new javax.swing.JTextField();
        BOOKROOMEMAIL = new javax.swing.JTextField();
        BOOKROOMLASTNAME = new javax.swing.JTextField();
        BOOKROOMROOMSIZE = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        BOOKROOMCANCELBUTTON = new javax.swing.JButton();
        BOOKROOMCONFIRMBUTTON = new javax.swing.JButton();
        BOOKROOMFeedback = new javax.swing.JLabel();
        SHOWREGINFO = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        REGINFOFIRSTNAME = new javax.swing.JTextField();
        REGINFOADRESS = new javax.swing.JTextField();
        REGINFOTRAVELAGENCY = new javax.swing.JTextField();
        REGINFOPHONE = new javax.swing.JTextField();
        REGINFOROOMSIZE = new javax.swing.JTextField();
        REGINFOROOMNUMBER = new javax.swing.JTextField();
        REGINFOLASTNAME = new javax.swing.JTextField();
        REGINFOCOUNTRY = new javax.swing.JTextField();
        REGINFOEMAIL = new javax.swing.JTextField();
        REGINFOBACKBUTTON = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        LOGIN = new javax.swing.JPanel();
        USERNAME = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LOGINBUTTON = new javax.swing.JButton();
        GETFEEDBACK = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CREATEUSERBUTTON = new javax.swing.JButton();
        CREATEUSERPANEL = new javax.swing.JPanel();
        LABEL1 = new javax.swing.JLabel();
        CREATEUSERFULLNAME = new javax.swing.JTextField();
        CREATEUSERGENERATEBUTTON = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CREATEUSERUSERNAME = new javax.swing.JTextField();
        CREATEUSERPASSWORD = new javax.swing.JTextField();
        CREATEUSERSAVEUSER = new javax.swing.JButton();
        CREATEUSERBACKBUTTON = new javax.swing.JButton();
        SHOWBOOKEDROOMS = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DELETERESERVATION = new javax.swing.JButton();
        SHOWREGINFOBUTTON = new javax.swing.JButton();
        BACKBUTTONBOOKEDROOMS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SHOWBOOKEDROOMSTEXTAREA = new javax.swing.JTextArea();
        SHOWSTANDBYROOMS = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        STANDBYROOMTEXTAREA = new javax.swing.JTextArea();
        STANDBYROOMBACKBUTTON = new javax.swing.JButton();
        STANDBYROOMDECLINEBUTTON = new javax.swing.JButton();
        STANDBYROOMACCEPTBUTTON = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        LOGOUT.setText("LOG OUT");

        BOOKROOMBUTTON.setText("BOOK ROOM");
        BOOKROOMBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BOOKROOMBUTTONActionPerformed(evt);
            }
        });

        STANDBYBUTTON.setText("SHOW STANDBY ROOMS");

        SHOWBOOKEDBUTTON.setText("SHOW BOOKED ROOMS");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        jLabel5.setText("WELCOME TO CASABLANCA HOTEL RESERVATION");

        javax.swing.GroupLayout WELCOMELayout = new javax.swing.GroupLayout(WELCOME);
        WELCOME.setLayout(WELCOMELayout);
        WELCOMELayout.setHorizontalGroup(
            WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WELCOMELayout.createSequentialGroup()
                .addGap(0, 125, Short.MAX_VALUE)
                .addGroup(WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WELCOMELayout.createSequentialGroup()
                        .addComponent(LOGOUT)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WELCOMELayout.createSequentialGroup()
                        .addGroup(WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(WELCOMELayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(STANDBYBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SHOWBOOKEDBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BOOKROOMBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5))
                        .addGap(112, 112, 112))))
        );
        WELCOMELayout.setVerticalGroup(
            WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WELCOMELayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(SHOWBOOKEDBUTTON)
                .addGap(18, 18, 18)
                .addComponent(STANDBYBUTTON)
                .addGap(18, 18, 18)
                .addComponent(BOOKROOMBUTTON)
                .addGap(71, 71, 71)
                .addComponent(LOGOUT)
                .addGap(47, 47, 47))
        );

        getContentPane().add(WELCOME, "card3");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("START DATE");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("END DATE");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ROOM SIZE");

        CHOOSEDATESTARTDATE.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CHOOSEDATESTARTDATEActionPerformed(evt);
            }
        });

        CHOOSEDATEBACKBUTTON.setText("BACK");
        CHOOSEDATEBACKBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CHOOSEDATEBACKBUTTONActionPerformed(evt);
            }
        });

        CHOOSEDATESEARCHBUTTON.setText("SEARCH");
        CHOOSEDATESEARCHBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CHOOSEDATESEARCHBUTTONActionPerformed(evt);
            }
        });

        CHOOSEDATECOMBOBOX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CHOOSEDATEDATEFORMAT.setText("DD-MM-YY");

        CHOOSEDATEDATEFORMAT2.setText("DD-MM-YY");

        javax.swing.GroupLayout CHOOSEDATELayout = new javax.swing.GroupLayout(CHOOSEDATE);
        CHOOSEDATE.setLayout(CHOOSEDATELayout);
        CHOOSEDATELayout.setHorizontalGroup(
            CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CHOOSEDATELayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(CHOOSEDATEFEEDBACKLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CHOOSEDATELayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CHOOSEDATELayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(CHOOSEDATECOMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(CHOOSEDATELayout.createSequentialGroup()
                            .addComponent(CHOOSEDATEBACKBUTTON)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CHOOSEDATESEARCHBUTTON))
                        .addGroup(CHOOSEDATELayout.createSequentialGroup()
                            .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CHOOSEDATESTARTDATE)
                                .addComponent(CHOOSEDATEENDDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CHOOSEDATEDATEFORMAT)
                                .addComponent(CHOOSEDATEDATEFORMAT2))
                            .addGap(25, 25, 25))))
                .addGap(161, 161, 161))
        );
        CHOOSEDATELayout.setVerticalGroup(
            CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CHOOSEDATELayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHOOSEDATESTARTDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(CHOOSEDATEDATEFORMAT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHOOSEDATEENDDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CHOOSEDATEDATEFORMAT2))
                .addGap(18, 18, 18)
                .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CHOOSEDATECOMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(CHOOSEDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHOOSEDATESEARCHBUTTON)
                    .addComponent(CHOOSEDATEBACKBUTTON))
                .addGap(144, 144, 144)
                .addComponent(CHOOSEDATEFEEDBACKLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(CHOOSEDATE, "card4");

        jLabel16.setText("ROOM#");

        jLabel17.setText("ROOM SIZE");

        jLabel18.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        jLabel18.setText("SHOW AVAILABLE ROOMS");

        AVAILABLEROOMSBOOKBUTTON.setText("BOOK");
        AVAILABLEROOMSBOOKBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AVAILABLEROOMSBOOKBUTTONActionPerformed(evt);
            }
        });

        AVAILABLEROOMSBACKBUTTON.setText("BACK");
        AVAILABLEROOMSBACKBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AVAILABLEROOMSBACKBUTTONActionPerformed(evt);
            }
        });

        SHOWAVAILABLELIST.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        SHOWAVAILABLELIST.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(SHOWAVAILABLELIST);

        javax.swing.GroupLayout SHOWAVAILABLEROOMSLayout = new javax.swing.GroupLayout(SHOWAVAILABLEROOMS);
        SHOWAVAILABLEROOMS.setLayout(SHOWAVAILABLEROOMSLayout);
        SHOWAVAILABLEROOMSLayout.setHorizontalGroup(
            SHOWAVAILABLEROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SHOWAVAILABLEROOMSLayout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addGroup(SHOWAVAILABLEROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(SHOWAVAILABLEROOMSLayout.createSequentialGroup()
                        .addGroup(SHOWAVAILABLEROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SHOWAVAILABLEROOMSLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(100, 100, 100)
                                .addComponent(jLabel17))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(SHOWAVAILABLEROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AVAILABLEROOMSBOOKBUTTON)
                            .addComponent(AVAILABLEROOMSBACKBUTTON))))
                .addGap(96, 96, 96))
        );
        SHOWAVAILABLEROOMSLayout.setVerticalGroup(
            SHOWAVAILABLEROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWAVAILABLEROOMSLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(SHOWAVAILABLEROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SHOWAVAILABLEROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SHOWAVAILABLEROOMSLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AVAILABLEROOMSBOOKBUTTON)
                        .addGap(18, 18, 18)
                        .addComponent(AVAILABLEROOMSBACKBUTTON))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );

        getContentPane().add(SHOWAVAILABLEROOMS, "card7");

        BOOKROOMFIRSTNAME.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BOOKROOMFIRSTNAMEActionPerformed(evt);
            }
        });

        BOOKROOMROOMNUMBER.setEditable(false);

        BOOKROOMROOMSIZE.setEditable(false);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("FIRST NAME(S)");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("ADDRESS");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("PHONE");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("TRAVEL AGENCY");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("ROOM SIZE");

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("ROOM#");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("LAST NAME");

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("COUNTRY");

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("EMAIL");

        BOOKROOMCANCELBUTTON.setText("CANCEL");
        BOOKROOMCANCELBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BOOKROOMCANCELBUTTONActionPerformed(evt);
            }
        });

        BOOKROOMCONFIRMBUTTON.setText("CONFIRM");
        BOOKROOMCONFIRMBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BOOKROOMCONFIRMBUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BOOKROOMLayout = new javax.swing.GroupLayout(BOOKROOM);
        BOOKROOM.setLayout(BOOKROOMLayout);
        BOOKROOMLayout.setHorizontalGroup(
            BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BOOKROOMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BOOKROOMLayout.createSequentialGroup()
                        .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BOOKROOMLayout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BOOKROOMCOUNTRY, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BOOKROOMLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BOOKROOMFIRSTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BOOKROOMLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(BOOKROOMLayout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BOOKROOMPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BOOKROOMLayout.createSequentialGroup()
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BOOKROOMEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BOOKROOMLayout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BOOKROOMLASTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BOOKROOMLayout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BOOKROOMADRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BOOKROOMLayout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BOOKROOMTRAVELAGENCY, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(115, 115, 115)
                        .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)))
                    .addGroup(BOOKROOMLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(BOOKROOMFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BOOKROOMCANCELBUTTON)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BOOKROOMCONFIRMBUTTON)
                    .addComponent(BOOKROOMROOMSIZE, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOOKROOMROOMNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(31, 31, 31))
        );
        BOOKROOMLayout.setVerticalGroup(
            BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BOOKROOMLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BOOKROOMLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOOKROOMFIRSTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel26)
                    .addComponent(BOOKROOMROOMSIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOOKROOMLASTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(BOOKROOMROOMNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(BOOKROOMCOUNTRY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(BOOKROOMADRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BOOKROOMLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel21))
                    .addComponent(BOOKROOMPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOOKROOMEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(BOOKROOMTRAVELAGENCY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BOOKROOMLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(BOOKROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BOOKROOMCANCELBUTTON)
                            .addComponent(BOOKROOMCONFIRMBUTTON))
                        .addGap(18, 18, 18))
                    .addGroup(BOOKROOMLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(BOOKROOMFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(BOOKROOM, "card8");

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("FIRST NAME(S)");

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("ADRESS");

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("PHONE");

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("TRAVEL AGENCY");

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("ROOM SIZE");

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("ROOM#");

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel42.setText("LAST NAME");

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel43.setText("COUNTRY");

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel44.setText("EMAIL");

        REGINFOFIRSTNAME.setEditable(false);
        REGINFOFIRSTNAME.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                REGINFOFIRSTNAMEActionPerformed(evt);
            }
        });

        REGINFOADRESS.setEditable(false);

        REGINFOTRAVELAGENCY.setEditable(false);

        REGINFOPHONE.setEditable(false);

        REGINFOROOMSIZE.setEditable(false);

        REGINFOROOMNUMBER.setEditable(false);

        REGINFOLASTNAME.setEditable(false);

        REGINFOCOUNTRY.setEditable(false);

        REGINFOEMAIL.setEditable(false);

        REGINFOBACKBUTTON.setText("BACK");
        REGINFOBACKBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                REGINFOBACKBUTTONActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        jLabel48.setText("REGISTRATION INFORMATION");

        javax.swing.GroupLayout SHOWREGINFOLayout = new javax.swing.GroupLayout(SHOWREGINFO);
        SHOWREGINFO.setLayout(SHOWREGINFOLayout);
        SHOWREGINFOLayout.setHorizontalGroup(
            SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel48)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(REGINFOBACKBUTTON))
                    .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SHOWREGINFOLayout.createSequentialGroup()
                                .addComponent(REGINFOROOMSIZE, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(REGINFOROOMNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                                .addComponent(REGINFOTRAVELAGENCY, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(REGINFOFIRSTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(REGINFOPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(REGINFOADRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(REGINFOLASTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(REGINFOCOUNTRY, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(REGINFOEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        SHOWREGINFOLayout.setVerticalGroup(
            SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel48)
                .addGap(40, 40, 40)
                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(REGINFOFIRSTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(REGINFOADRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(REGINFOPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SHOWREGINFOLayout.createSequentialGroup()
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(REGINFOLASTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(REGINFOCOUNTRY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(REGINFOEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(REGINFOTRAVELAGENCY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SHOWREGINFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(REGINFOROOMNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(REGINFOROOMSIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(85, 85, 85)
                .addComponent(REGINFOBACKBUTTON)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        getContentPane().add(SHOWREGINFO, "card9");

        USERNAME.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                USERNAMEActionPerformed(evt);
            }
        });

        jLabel2.setText("PASSWORD");

        LOGINBUTTON.setText("LOG IN");

        GETFEEDBACK.setText("GET FEEDBACK");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        jLabel4.setText("PLEASE LOGIN  AS A STAFF");

        jLabel1.setText("USERNAME");

        CREATEUSERBUTTON.setText("CREATE USER");

        javax.swing.GroupLayout LOGINLayout = new javax.swing.GroupLayout(LOGIN);
        LOGIN.setLayout(LOGINLayout);
        LOGINLayout.setHorizontalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GETFEEDBACK)
                    .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGINLayout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGINLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGINLayout.createSequentialGroup()
                        .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CREATEUSERBUTTON)
                            .addComponent(LOGINBUTTON))
                        .addGap(48, 48, 48))))
        );
        LOGINLayout.setVerticalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CREATEUSERBUTTON))
                .addGap(26, 26, 26)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(GETFEEDBACK)
                .addGap(18, 18, 18)
                .addComponent(LOGINBUTTON)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        getContentPane().add(LOGIN, "card2");

        LABEL1.setText("FULL NAME");

        CREATEUSERFULLNAME.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CREATEUSERFULLNAMEActionPerformed(evt);
            }
        });

        CREATEUSERGENERATEBUTTON.setText("GENERATE ");
        CREATEUSERGENERATEBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CREATEUSERGENERATEBUTTONActionPerformed(evt);
            }
        });

        jLabel13.setText("USERNAME");

        jLabel14.setText("PASSWORD");

        CREATEUSERUSERNAME.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CREATEUSERUSERNAMEActionPerformed(evt);
            }
        });

        CREATEUSERPASSWORD.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CREATEUSERPASSWORDActionPerformed(evt);
            }
        });

        CREATEUSERSAVEUSER.setText("SAVE USER");

        CREATEUSERBACKBUTTON.setText("BACK");
        CREATEUSERBACKBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CREATEUSERBACKBUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CREATEUSERPANELLayout = new javax.swing.GroupLayout(CREATEUSERPANEL);
        CREATEUSERPANEL.setLayout(CREATEUSERPANELLayout);
        CREATEUSERPANELLayout.setHorizontalGroup(
            CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CREATEUSERPANELLayout.createSequentialGroup()
                .addGroup(CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(CREATEUSERPANELLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CREATEUSERPANELLayout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(LABEL1))))
                .addGap(18, 18, 18)
                .addGroup(CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CREATEUSERGENERATEBUTTON)
                    .addComponent(CREATEUSERFULLNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(CREATEUSERUSERNAME)
                    .addComponent(CREATEUSERPASSWORD))
                .addContainerGap(355, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CREATEUSERPANELLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CREATEUSERSAVEUSER, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(CREATEUSERBACKBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86))
        );
        CREATEUSERPANELLayout.setVerticalGroup(
            CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CREATEUSERPANELLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL1)
                    .addComponent(CREATEUSERFULLNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CREATEUSERGENERATEBUTTON)
                .addGap(18, 18, 18)
                .addGroup(CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CREATEUSERUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(29, 29, 29)
                .addGroup(CREATEUSERPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CREATEUSERPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(CREATEUSERSAVEUSER)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CREATEUSERBACKBUTTON)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        getContentPane().add(CREATEUSERPANEL, "card10");

        jLabel9.setText("ROOM#");

        jLabel10.setText("START DATE");

        jLabel11.setText("END DATE");

        DELETERESERVATION.setText("DELETE RESERVATION");
        DELETERESERVATION.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DELETERESERVATIONActionPerformed(evt);
            }
        });

        SHOWREGINFOBUTTON.setText("SHOW REGISTRAION INFO");
        SHOWREGINFOBUTTON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SHOWREGINFOBUTTONActionPerformed(evt);
            }
        });

        BACKBUTTONBOOKEDROOMS.setText("BACK");

        SHOWBOOKEDROOMSTEXTAREA.setColumns(20);
        SHOWBOOKEDROOMSTEXTAREA.setRows(5);
        jScrollPane1.setViewportView(SHOWBOOKEDROOMSTEXTAREA);

        javax.swing.GroupLayout SHOWBOOKEDROOMSLayout = new javax.swing.GroupLayout(SHOWBOOKEDROOMS);
        SHOWBOOKEDROOMS.setLayout(SHOWBOOKEDROOMSLayout);
        SHOWBOOKEDROOMSLayout.setHorizontalGroup(
            SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWBOOKEDROOMSLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
            .addGroup(SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SHOWBOOKEDROOMSLayout.createSequentialGroup()
                    .addGroup(SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SHOWBOOKEDROOMSLayout.createSequentialGroup()
                            .addGap(263, 263, 263)
                            .addGroup(SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SHOWREGINFOBUTTON)
                                    .addComponent(DELETERESERVATION, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(BACKBUTTONBOOKEDROOMS)))
                        .addGroup(SHOWBOOKEDROOMSLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel9)
                            .addGap(21, 21, 21)
                            .addComponent(jLabel10)
                            .addGap(33, 33, 33)
                            .addComponent(jLabel11)))
                    .addContainerGap(197, Short.MAX_VALUE)))
        );
        SHOWBOOKEDROOMSLayout.setVerticalGroup(
            SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWBOOKEDROOMSLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SHOWBOOKEDROOMSLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(SHOWBOOKEDROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11))
                    .addGap(18, 18, 18)
                    .addComponent(DELETERESERVATION)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(SHOWREGINFOBUTTON)
                    .addGap(148, 148, 148)
                    .addComponent(BACKBUTTONBOOKEDROOMS)
                    .addContainerGap(199, Short.MAX_VALUE)))
        );

        getContentPane().add(SHOWBOOKEDROOMS, "card5");

        STANDBYROOMTEXTAREA.setColumns(20);
        STANDBYROOMTEXTAREA.setRows(5);
        jScrollPane5.setViewportView(STANDBYROOMTEXTAREA);

        STANDBYROOMBACKBUTTON.setText("BACK");

        STANDBYROOMDECLINEBUTTON.setText("DECLINE");

        STANDBYROOMACCEPTBUTTON.setText("ACCEPT");

        jLabel59.setText("DAYS REMAIN");

        jLabel58.setText("END DATE");

        jLabel57.setText("START DATE");

        jLabel56.setText("ROOM#");

        javax.swing.GroupLayout SHOWSTANDBYROOMSLayout = new javax.swing.GroupLayout(SHOWSTANDBYROOMS);
        SHOWSTANDBYROOMS.setLayout(SHOWSTANDBYROOMSLayout);
        SHOWSTANDBYROOMSLayout.setHorizontalGroup(
            SHOWSTANDBYROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWSTANDBYROOMSLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(SHOWSTANDBYROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SHOWSTANDBYROOMSLayout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel57)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel59))
                    .addComponent(jScrollPane5))
                .addGap(28, 28, 28)
                .addGroup(SHOWSTANDBYROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(STANDBYROOMACCEPTBUTTON)
                    .addComponent(STANDBYROOMDECLINEBUTTON))
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SHOWSTANDBYROOMSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(STANDBYROOMBACKBUTTON)
                .addGap(20, 20, 20))
        );
        SHOWSTANDBYROOMSLayout.setVerticalGroup(
            SHOWSTANDBYROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWSTANDBYROOMSLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(SHOWSTANDBYROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(jLabel57)
                    .addComponent(jLabel58)
                    .addComponent(jLabel59))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SHOWSTANDBYROOMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SHOWSTANDBYROOMSLayout.createSequentialGroup()
                        .addComponent(STANDBYROOMACCEPTBUTTON)
                        .addGap(14, 14, 14)
                        .addComponent(STANDBYROOMDECLINEBUTTON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(STANDBYROOMBACKBUTTON)
                        .addGap(36, 36, 36))
                    .addGroup(SHOWSTANDBYROOMSLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(182, Short.MAX_VALUE))))
        );

        getContentPane().add(SHOWSTANDBYROOMS, "card6");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void USERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERNAMEActionPerformed

    private void CHOOSEDATESTARTDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHOOSEDATESTARTDATEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHOOSEDATESTARTDATEActionPerformed

    private void DELETERESERVATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETERESERVATIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DELETERESERVATIONActionPerformed

    private void SHOWREGINFOBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWREGINFOBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SHOWREGINFOBUTTONActionPerformed

    private void REGINFOFIRSTNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGINFOFIRSTNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGINFOFIRSTNAMEActionPerformed

    private void BOOKROOMFIRSTNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOKROOMFIRSTNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOOKROOMFIRSTNAMEActionPerformed

    private void CHOOSEDATESEARCHBUTTONActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CHOOSEDATESEARCHBUTTONActionPerformed
    {//GEN-HEADEREND:event_CHOOSEDATESEARCHBUTTONActionPerformed
        // my boookk button = search
        ArrayList<Room> rooms = new ArrayList();
        String sDate = CHOOSEDATESTARTDATE.getText();
        String eDate = CHOOSEDATEENDDATE.getText();
        String dateFormat = "dd-MM-yy";

        if (dv.isDateValid(sDate, dateFormat) && dv.isDateValid(eDate, dateFormat))
        {
            if (dv.isDateHigher(sDate, eDate, dateFormat))
            {
                if (CHOOSEDATECOMBOBOX.getSelectedItem().toString().equals("All"))
                {
                    rooms = con.getAllFreeRooms(sDate, eDate);
                } else
                {
                    int rSize = Integer.parseInt(CHOOSEDATECOMBOBOX.getSelectedItem().toString());
                    rooms = con.getSizeFreeRooms(sDate, eDate, rSize);
                }
                if (!rooms.isEmpty())
                {
                    fillAvailList(rooms);
                    CHOOSEDATE.setVisible(false);
                    SHOWAVAILABLEROOMS.setVisible(true);

                } else
                {
                    CHOOSEDATEFEEDBACKLABEL.setText("No available apartments!");
                }
            } else
            {
                CHOOSEDATEFEEDBACKLABEL.setText("End date is before start date!");
            }

        } else
        {
            CHOOSEDATEFEEDBACKLABEL.setText("Please enter a valid date.");
        }
    }//GEN-LAST:event_CHOOSEDATESEARCHBUTTONActionPerformed

    private void AVAILABLEROOMSBACKBUTTONActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AVAILABLEROOMSBACKBUTTONActionPerformed
    {//GEN-HEADEREND:event_AVAILABLEROOMSBACKBUTTONActionPerformed
        SHOWAVAILABLEROOMS.setVisible(false);
        CHOOSEDATE.setVisible(true);
        CHOOSEDATEFEEDBACKLABEL.setText("");

    }//GEN-LAST:event_AVAILABLEROOMSBACKBUTTONActionPerformed

    private void AVAILABLEROOMSBOOKBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVAILABLEROOMSBOOKBUTTONActionPerformed
        SHOWAVAILABLEROOMS.setVisible(false);
        BOOKROOM.setVisible(true);
        String r_id = SHOWAVAILABLELIST.getSelectedValue().toString();
        String room_id = r_id.substring(0, r_id.length() - 6);
        BOOKROOMROOMNUMBER.setText(room_id);
        
        String r_size = r_id.substring(r_id.length()-1, r_id.length());
        BOOKROOMROOMSIZE.setText(r_size);
    }//GEN-LAST:event_AVAILABLEROOMSBOOKBUTTONActionPerformed

    private void CREATEUSERUSERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEUSERUSERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CREATEUSERUSERNAMEActionPerformed

    private void CREATEUSERPASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEUSERPASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CREATEUSERPASSWORDActionPerformed

    private void CREATEUSERBACKBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEUSERBACKBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CREATEUSERBACKBUTTONActionPerformed

    private void CREATEUSERGENERATEBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEUSERGENERATEBUTTONActionPerformed

        String fullName = CREATEUSERFULLNAME.getText();
        CreateUserStaff cus = new CreateUserStaff(fullName);
        CREATEUSERUSERNAME.setText(cus.getuserName());
        CREATEUSERPASSWORD.setText(cus.getPassword());
    }//GEN-LAST:event_CREATEUSERGENERATEBUTTONActionPerformed

    private void CREATEUSERFULLNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEUSERFULLNAMEActionPerformed
    }//GEN-LAST:event_CREATEUSERFULLNAMEActionPerformed

    private void BOOKROOMBUTTONActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BOOKROOMBUTTONActionPerformed
    {//GEN-HEADEREND:event_BOOKROOMBUTTONActionPerformed
        WELCOME.setVisible(false);
        CHOOSEDATE.setVisible(true);
        CHOOSEDATESTARTDATE.setText("");
        CHOOSEDATEENDDATE.setText("");
       
    }//GEN-LAST:event_BOOKROOMBUTTONActionPerformed

    private void CHOOSEDATEBACKBUTTONActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CHOOSEDATEBACKBUTTONActionPerformed
    {//GEN-HEADEREND:event_CHOOSEDATEBACKBUTTONActionPerformed
        CHOOSEDATE.setVisible(false);
        WELCOME.setVisible(true);
    }//GEN-LAST:event_CHOOSEDATEBACKBUTTONActionPerformed

    private void REGINFOBACKBUTTONActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_REGINFOBACKBUTTONActionPerformed
    {//GEN-HEADEREND:event_REGINFOBACKBUTTONActionPerformed

    }//GEN-LAST:event_REGINFOBACKBUTTONActionPerformed

    private void BOOKROOMCONFIRMBUTTONActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BOOKROOMCONFIRMBUTTONActionPerformed
    {//GEN-HEADEREND:event_BOOKROOMCONFIRMBUTTONActionPerformed
        String firstname = BOOKROOMFIRSTNAME.getText();
        String familyname = BOOKROOMLASTNAME.getText();
        String address = BOOKROOMADRESS.getText();
        String country = BOOKROOMCOUNTRY.getText();
        int phone = Integer.parseInt(BOOKROOMPHONE.getText());
        String email = BOOKROOMEMAIL.getText();
        int travel_agency = Integer.parseInt(BOOKROOMTRAVELAGENCY.getText());
        String fullname = firstname + " " + familyname;
        CreateUserStaff cus = new CreateUserStaff(fullname);
        String username = cus.getuserName();
        String password = cus.getPassword();

        Guest g = con.createNewGuest(firstname, familyname, address, country, phone, email,
                travel_agency, username, password);

        if (g != null)
        {
            String r_id = SHOWAVAILABLELIST.getSelectedValue().toString();
            String str = r_id.substring(0, r_id.length() - 6);
            int room_id = Integer.parseInt(str);
            Booking b = con.createNewBooking(CHOOSEDATESTARTDATE.getText(),
                    CHOOSEDATEENDDATE.getText(), room_id, g.getGuest_id());

            if (b != null)
            {
                BOOKROOMADRESS.setText("");
                BOOKROOMCOUNTRY.setText("");
                BOOKROOMEMAIL.setText("");
                BOOKROOMFIRSTNAME.setText("");
                BOOKROOMLASTNAME.setText("");
                BOOKROOMPHONE.setText("");
                BOOKROOMROOMNUMBER.setText("");
                BOOKROOMROOMSIZE.setText("");
                BOOKROOMTRAVELAGENCY.setText("");
                BOOKROOM.setVisible(false);
                WELCOME.setVisible(true);
            } else
            {
                BOOKROOMFeedback.setText("Failed creating booking");
            }
        } else
        {
            BOOKROOMFeedback.setText("Failed creating guest");
        }
    }//GEN-LAST:event_BOOKROOMCONFIRMBUTTONActionPerformed

    private void BOOKROOMCANCELBUTTONActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BOOKROOMCANCELBUTTONActionPerformed
    {//GEN-HEADEREND:event_BOOKROOMCANCELBUTTONActionPerformed
        BOOKROOMADRESS.setText("");
        BOOKROOMCOUNTRY.setText("");
        BOOKROOMEMAIL.setText("");
        BOOKROOMFIRSTNAME.setText("");
        BOOKROOMLASTNAME.setText("");
        BOOKROOMPHONE.setText("");
        BOOKROOMROOMNUMBER.setText("");
        BOOKROOMROOMSIZE.setText("");
        BOOKROOMTRAVELAGENCY.setText("");
        BOOKROOM.setVisible(false);
        WELCOME.setVisible(true);
    }//GEN-LAST:event_BOOKROOMCANCELBUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Casablanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Casablanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Casablanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Casablanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Casablanca().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AVAILABLEROOMSBACKBUTTON;
    private javax.swing.JButton AVAILABLEROOMSBOOKBUTTON;
    private javax.swing.JButton BACKBUTTONBOOKEDROOMS;
    private javax.swing.JPanel BOOKROOM;
    private javax.swing.JTextField BOOKROOMADRESS;
    private javax.swing.JButton BOOKROOMBUTTON;
    private javax.swing.JButton BOOKROOMCANCELBUTTON;
    private javax.swing.JButton BOOKROOMCONFIRMBUTTON;
    private javax.swing.JTextField BOOKROOMCOUNTRY;
    private javax.swing.JTextField BOOKROOMEMAIL;
    private javax.swing.JTextField BOOKROOMFIRSTNAME;
    private javax.swing.JLabel BOOKROOMFeedback;
    private javax.swing.JTextField BOOKROOMLASTNAME;
    private javax.swing.JTextField BOOKROOMPHONE;
    private javax.swing.JTextField BOOKROOMROOMNUMBER;
    private javax.swing.JTextField BOOKROOMROOMSIZE;
    private javax.swing.JTextField BOOKROOMTRAVELAGENCY;
    private javax.swing.JPanel CHOOSEDATE;
    private javax.swing.JButton CHOOSEDATEBACKBUTTON;
    private javax.swing.JComboBox CHOOSEDATECOMBOBOX;
    private javax.swing.JLabel CHOOSEDATEDATEFORMAT;
    private javax.swing.JLabel CHOOSEDATEDATEFORMAT2;
    private javax.swing.JTextField CHOOSEDATEENDDATE;
    private javax.swing.JLabel CHOOSEDATEFEEDBACKLABEL;
    private javax.swing.JButton CHOOSEDATESEARCHBUTTON;
    private javax.swing.JTextField CHOOSEDATESTARTDATE;
    private javax.swing.JButton CREATEUSERBACKBUTTON;
    private javax.swing.JButton CREATEUSERBUTTON;
    private javax.swing.JTextField CREATEUSERFULLNAME;
    private javax.swing.JButton CREATEUSERGENERATEBUTTON;
    private javax.swing.JPanel CREATEUSERPANEL;
    private javax.swing.JTextField CREATEUSERPASSWORD;
    private javax.swing.JButton CREATEUSERSAVEUSER;
    private javax.swing.JTextField CREATEUSERUSERNAME;
    private javax.swing.JButton DELETERESERVATION;
    private javax.swing.JLabel GETFEEDBACK;
    private javax.swing.JLabel LABEL1;
    private javax.swing.JPanel LOGIN;
    private javax.swing.JButton LOGINBUTTON;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JTextField PASSWORD;
    private javax.swing.JTextField REGINFOADRESS;
    private javax.swing.JButton REGINFOBACKBUTTON;
    private javax.swing.JTextField REGINFOCOUNTRY;
    private javax.swing.JTextField REGINFOEMAIL;
    private javax.swing.JTextField REGINFOFIRSTNAME;
    private javax.swing.JTextField REGINFOLASTNAME;
    private javax.swing.JTextField REGINFOPHONE;
    private javax.swing.JTextField REGINFOROOMNUMBER;
    private javax.swing.JTextField REGINFOROOMSIZE;
    private javax.swing.JTextField REGINFOTRAVELAGENCY;
    private javax.swing.JList SHOWAVAILABLELIST;
    private javax.swing.JPanel SHOWAVAILABLEROOMS;
    private javax.swing.JButton SHOWBOOKEDBUTTON;
    private javax.swing.JPanel SHOWBOOKEDROOMS;
    private javax.swing.JTextArea SHOWBOOKEDROOMSTEXTAREA;
    private javax.swing.JPanel SHOWREGINFO;
    private javax.swing.JButton SHOWREGINFOBUTTON;
    private javax.swing.JPanel SHOWSTANDBYROOMS;
    private javax.swing.JButton STANDBYBUTTON;
    private javax.swing.JButton STANDBYROOMACCEPTBUTTON;
    private javax.swing.JButton STANDBYROOMBACKBUTTON;
    private javax.swing.JButton STANDBYROOMDECLINEBUTTON;
    private javax.swing.JTextArea STANDBYROOMTEXTAREA;
    private javax.swing.JTextField USERNAME;
    private javax.swing.JPanel WELCOME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables

    private void fillChooseCombo()
    {
        CHOOSEDATECOMBOBOX.removeAllItems();
        CHOOSEDATECOMBOBOX.addItem("1");
        CHOOSEDATECOMBOBOX.addItem("2");
        CHOOSEDATECOMBOBOX.addItem("5");
        CHOOSEDATECOMBOBOX.addItem("All");
    }

    private void fillAvailList(ArrayList<Room> rooms)
    {
        SHOWAVAILABLELIST.removeAll();
        Object[] o = rooms.toArray(new Object[0]);
        SHOWAVAILABLELIST.setListData(o);

    }

    private void showMenuHideOthers()
    {
        WELCOME.setVisible(true);
        CHOOSEDATE.setVisible(false);
        SHOWAVAILABLEROOMS.setVisible(false);
        BOOKROOM.setVisible(false);
        SHOWREGINFO.setVisible(false);
        LOGIN.setVisible(false);
        CREATEUSERPANEL.setVisible(false);
        SHOWBOOKEDROOMS.setVisible(false);
        SHOWSTANDBYROOMS.setVisible(false);
    }
}
