/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentation;

/**
 *
 * @author Filipovic
 */
public class GuestBooking extends javax.swing.JFrame {

    /**
     * Creates new form GuestBooking
     */
    public GuestBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LOGIN = new javax.swing.JPanel();
        GUESTUSERNAME = new javax.swing.JTextField();
        GUESTPASSWORD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GUESTFEEDBACK = new javax.swing.JLabel();
        GUESTLOGIN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        WELCOME = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BOOKFACILITYBUTTON = new javax.swing.JButton();
        CHECKBOOKINGBUTTON = new javax.swing.JButton();
        LOGOUTBUTTON = new javax.swing.JButton();
        BOOKFACILITY = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        VOLLEYBALL = new javax.swing.JButton();
        BADMINTON = new javax.swing.JButton();
        TENNIS = new javax.swing.JButton();
        GOLF = new javax.swing.JButton();
        HANDBALL = new javax.swing.JButton();
        SWIMMING = new javax.swing.JButton();
        FITNESS = new javax.swing.JButton();
        PINGPONG = new javax.swing.JButton();
        HILLYGROUND = new javax.swing.JButton();
        BOOKFACILITYBACKBUTTON = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel8.setText("INSTRUCTOR IS AVAILABLE");

        jLabel10.setText("INSTRUCTOR IS AVAILABLE");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        GUESTUSERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUESTUSERNAMEActionPerformed(evt);
            }
        });

        jLabel1.setText("USERNAME");

        jLabel2.setText("PASSWORD");

        GUESTFEEDBACK.setText("GET FEEDBACK");

        GUESTLOGIN.setText("LOGIN");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        jLabel5.setText("PLEASE LOGIN AS A GUEST");

        javax.swing.GroupLayout LOGINLayout = new javax.swing.GroupLayout(LOGIN);
        LOGIN.setLayout(LOGINLayout);
        LOGINLayout.setHorizontalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGINLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUESTLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GUESTFEEDBACK)
                    .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GUESTUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GUESTPASSWORD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        LOGINLayout.setVerticalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addGap(48, 48, 48)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUESTUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUESTPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addComponent(GUESTFEEDBACK)
                .addGap(18, 18, 18)
                .addComponent(GUESTLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(LOGIN, "card2");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        jLabel6.setText("WELCOME");

        BOOKFACILITYBUTTON.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BOOKFACILITYBUTTON.setText("BOOK FACILITY");
        BOOKFACILITYBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOOKFACILITYBUTTONActionPerformed(evt);
            }
        });

        CHECKBOOKINGBUTTON.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CHECKBOOKINGBUTTON.setText("CHECK BOOKING");
        CHECKBOOKINGBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECKBOOKINGBUTTONActionPerformed(evt);
            }
        });

        LOGOUTBUTTON.setText("LOGOUT");
        LOGOUTBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTBUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WELCOMELayout = new javax.swing.GroupLayout(WELCOME);
        WELCOME.setLayout(WELCOMELayout);
        WELCOMELayout.setHorizontalGroup(
            WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WELCOMELayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CHECKBOOKINGBUTTON)
                    .addComponent(BOOKFACILITYBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 236, Short.MAX_VALUE))
            .addGroup(WELCOMELayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WELCOMELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LOGOUTBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        WELCOMELayout.setVerticalGroup(
            WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WELCOMELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addComponent(BOOKFACILITYBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(CHECKBOOKINGBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(LOGOUTBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(WELCOME, "card3");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        jLabel7.setText("BOOK FACILITY");

        VOLLEYBALL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VOLLEYBALL.setText("VOLLEYBALL");
        VOLLEYBALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLLEYBALLActionPerformed(evt);
            }
        });

        BADMINTON.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BADMINTON.setText("BADMINTON");
        BADMINTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BADMINTONActionPerformed(evt);
            }
        });

        TENNIS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TENNIS.setText("TENNIS");
        TENNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TENNISActionPerformed(evt);
            }
        });

        GOLF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GOLF.setText("GOLF");
        GOLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOLFActionPerformed(evt);
            }
        });

        HANDBALL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HANDBALL.setText("HANDBALL");
        HANDBALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HANDBALLActionPerformed(evt);
            }
        });

        SWIMMING.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SWIMMING.setText("SWIMMING");
        SWIMMING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SWIMMINGActionPerformed(evt);
            }
        });

        FITNESS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FITNESS.setText("FITNESS");
        FITNESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FITNESSActionPerformed(evt);
            }
        });

        PINGPONG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PINGPONG.setText("PING PONG");
        PINGPONG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PINGPONGActionPerformed(evt);
            }
        });

        HILLYGROUND.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HILLYGROUND.setText("HILLY GROUND");
        HILLYGROUND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HILLYGROUNDActionPerformed(evt);
            }
        });

        BOOKFACILITYBACKBUTTON.setText("BACK");
        BOOKFACILITYBACKBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOOKFACILITYBACKBUTTONActionPerformed(evt);
            }
        });

        jLabel4.setText("INSTRUCTOR IS AVAILABLE");

        jLabel9.setText("INSTRUCTOR IS AVAILABLE");

        jLabel11.setText("INSTRUCTOR IS AVAILABLE");

        jLabel12.setText("INSTRUCTOR IS AVAILABLE");

        javax.swing.GroupLayout BOOKFACILITYLayout = new javax.swing.GroupLayout(BOOKFACILITY);
        BOOKFACILITY.setLayout(BOOKFACILITYLayout);
        BOOKFACILITYLayout.setHorizontalGroup(
            BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BOOKFACILITYLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BOOKFACILITYBACKBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                            .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                                    .addComponent(HANDBALL, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(FITNESS, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BOOKFACILITYLayout.createSequentialGroup()
                                    .addComponent(SWIMMING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(HILLYGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PINGPONG, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(GOLF, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VOLLEYBALL, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jLabel11)))))
                    .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                        .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TENNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9))
                            .addComponent(BADMINTON, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(65, 65, 65))
            .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BOOKFACILITYLayout.setVerticalGroup(
            BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PINGPONG, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BADMINTON, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TENNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HANDBALL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GOLF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FITNESS, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HILLYGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VOLLEYBALL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SWIMMING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel12)
                .addGap(1, 1, 1)
                .addComponent(BOOKFACILITYBACKBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(BOOKFACILITY, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUESTUSERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUESTUSERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUESTUSERNAMEActionPerformed

    private void BOOKFACILITYBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOKFACILITYBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOOKFACILITYBUTTONActionPerformed

    private void CHECKBOOKINGBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECKBOOKINGBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHECKBOOKINGBUTTONActionPerformed

    private void LOGOUTBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGOUTBUTTONActionPerformed

    private void BOOKFACILITYBACKBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOKFACILITYBACKBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOOKFACILITYBACKBUTTONActionPerformed

    private void HILLYGROUNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HILLYGROUNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HILLYGROUNDActionPerformed

    private void PINGPONGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PINGPONGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PINGPONGActionPerformed

    private void FITNESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FITNESSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FITNESSActionPerformed

    private void SWIMMINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SWIMMINGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SWIMMINGActionPerformed

    private void HANDBALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HANDBALLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HANDBALLActionPerformed

    private void GOLFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOLFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GOLFActionPerformed

    private void TENNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TENNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TENNISActionPerformed

    private void BADMINTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BADMINTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BADMINTONActionPerformed

    private void VOLLEYBALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLLEYBALLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VOLLEYBALLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BADMINTON;
    private javax.swing.JPanel BOOKFACILITY;
    private javax.swing.JButton BOOKFACILITYBACKBUTTON;
    private javax.swing.JButton BOOKFACILITYBUTTON;
    private javax.swing.JButton CHECKBOOKINGBUTTON;
    private javax.swing.JButton FITNESS;
    private javax.swing.JButton GOLF;
    private javax.swing.JLabel GUESTFEEDBACK;
    private javax.swing.JButton GUESTLOGIN;
    private javax.swing.JTextField GUESTPASSWORD;
    private javax.swing.JTextField GUESTUSERNAME;
    private javax.swing.JButton HANDBALL;
    private javax.swing.JButton HILLYGROUND;
    private javax.swing.JPanel LOGIN;
    private javax.swing.JButton LOGOUTBUTTON;
    private javax.swing.JButton PINGPONG;
    private javax.swing.JButton SWIMMING;
    private javax.swing.JButton TENNIS;
    private javax.swing.JButton VOLLEYBALL;
    private javax.swing.JPanel WELCOME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
