/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentation;

/**
 *
 * @author Filipovic
 */
public class GuestBooking extends javax.swing.JFrame {

    /**
     * Creates new form GuestBooking
     */
    public GuestBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LOGIN = new javax.swing.JPanel();
        GUESTUSERNAME = new javax.swing.JTextField();
        GUESTPASSWORD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GUESTFEEDBACK = new javax.swing.JLabel();
        GUESTLOGIN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        WELCOME = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BOOKFACILITYBUTTON = new javax.swing.JButton();
        CHECKBOOKINGBUTTON = new javax.swing.JButton();
        LOGOUTBUTTON = new javax.swing.JButton();
        BOOKFACILITY = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        VOLLEYBALL = new javax.swing.JButton();
        BADMINTON = new javax.swing.JButton();
        TENNIS = new javax.swing.JButton();
        GOLF = new javax.swing.JButton();
        HANDBALL = new javax.swing.JButton();
        SWIMMING = new javax.swing.JButton();
        FITNESS = new javax.swing.JButton();
        PINGPONG = new javax.swing.JButton();
        HILLYGROUND = new javax.swing.JButton();
        BOOKFACILITYBACKBUTTON = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        YOUWANTINSTRUCTOR = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        INSTRUCTORYESBUTTON = new javax.swing.JButton();
        INSTRUCTORNOBUTTON = new javax.swing.JButton();
        SHOWTIMEANDDATE = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        SHOWTIMEDATECOMBOBOX = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        SHOWTIMEDATELIST = new javax.swing.JList();
        SHOWTIMEDATEBOOKBUTTON = new javax.swing.JButton();
        YOUARENOWBOOKEDIN = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        THANKYOUBUTTON = new javax.swing.JButton();
        DELETEBOOKING = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DELETEBOOKINGLIST = new javax.swing.JList();
        jLabel17 = new javax.swing.JLabel();
        DELETEBOOKINGBACKBUTTON = new javax.swing.JButton();
        DELETEBOOKINGBUTTON = new javax.swing.JButton();
        YOUHAVEDELETED = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        YOUHAVEDELETEDBACKBUTTON = new javax.swing.JButton();

        jLabel8.setText("INSTRUCTOR IS AVAILABLE");

        jLabel10.setText("INSTRUCTOR IS AVAILABLE");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        GUESTUSERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUESTUSERNAMEActionPerformed(evt);
            }
        });

        jLabel1.setText("USERNAME");

        jLabel2.setText("PASSWORD");

        GUESTFEEDBACK.setForeground(new java.awt.Color(255, 0, 0));
        GUESTFEEDBACK.setText("GET FEEDBACK");

        GUESTLOGIN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        GUESTLOGIN.setForeground(new java.awt.Color(102, 102, 0));
        GUESTLOGIN.setText("LOGIN");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 0));
        jLabel5.setText("PLEASE LOGIN AS A GUEST");

        javax.swing.GroupLayout LOGINLayout = new javax.swing.GroupLayout(LOGIN);
        LOGIN.setLayout(LOGINLayout);
        LOGINLayout.setHorizontalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUESTLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GUESTFEEDBACK)
                    .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GUESTUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GUESTPASSWORD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGINLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        LOGINLayout.setVerticalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUESTUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUESTPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addComponent(GUESTFEEDBACK)
                .addGap(18, 18, 18)
                .addComponent(GUESTLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(LOGIN, "card2");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 0));
        jLabel6.setText("WELCOME");

        BOOKFACILITYBUTTON.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BOOKFACILITYBUTTON.setForeground(new java.awt.Color(102, 102, 0));
        BOOKFACILITYBUTTON.setText("BOOK FACILITY");
        BOOKFACILITYBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOOKFACILITYBUTTONActionPerformed(evt);
            }
        });

        CHECKBOOKINGBUTTON.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CHECKBOOKINGBUTTON.setForeground(new java.awt.Color(102, 102, 0));
        CHECKBOOKINGBUTTON.setText("DELETE BOOKING");
        CHECKBOOKINGBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECKBOOKINGBUTTONActionPerformed(evt);
            }
        });

        LOGOUTBUTTON.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LOGOUTBUTTON.setForeground(new java.awt.Color(102, 102, 0));
        LOGOUTBUTTON.setText("LOGOUT");
        LOGOUTBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTBUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WELCOMELayout = new javax.swing.GroupLayout(WELCOME);
        WELCOME.setLayout(WELCOMELayout);
        WELCOMELayout.setHorizontalGroup(
            WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WELCOMELayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CHECKBOOKINGBUTTON)
                    .addComponent(BOOKFACILITYBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(WELCOMELayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WELCOMELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LOGOUTBUTTON)
                .addGap(33, 33, 33))
        );
        WELCOMELayout.setVerticalGroup(
            WELCOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WELCOMELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addComponent(BOOKFACILITYBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(CHECKBOOKINGBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(LOGOUTBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(WELCOME, "card3");

        jLabel7.setFont(new java.awt.Font("AngsanaUPC", 2, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 0));
        jLabel7.setText("BOOK FACILITY");

        VOLLEYBALL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VOLLEYBALL.setForeground(new java.awt.Color(102, 102, 0));
        VOLLEYBALL.setText("VOLLEYBALL");
        VOLLEYBALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLLEYBALLActionPerformed(evt);
            }
        });

        BADMINTON.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BADMINTON.setForeground(new java.awt.Color(102, 102, 0));
        BADMINTON.setText("BADMINTON");
        BADMINTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BADMINTONActionPerformed(evt);
            }
        });

        TENNIS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TENNIS.setForeground(new java.awt.Color(102, 102, 0));
        TENNIS.setText("TENNIS");
        TENNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TENNISActionPerformed(evt);
            }
        });

        GOLF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GOLF.setForeground(new java.awt.Color(102, 102, 0));
        GOLF.setText("GOLF");
        GOLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOLFActionPerformed(evt);
            }
        });

        HANDBALL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HANDBALL.setForeground(new java.awt.Color(102, 102, 0));
        HANDBALL.setText("HANDBALL");
        HANDBALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HANDBALLActionPerformed(evt);
            }
        });

        SWIMMING.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SWIMMING.setForeground(new java.awt.Color(102, 102, 0));
        SWIMMING.setText("SWIMMING");
        SWIMMING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SWIMMINGActionPerformed(evt);
            }
        });

        FITNESS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FITNESS.setForeground(new java.awt.Color(102, 102, 0));
        FITNESS.setText("FITNESS");
        FITNESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FITNESSActionPerformed(evt);
            }
        });

        PINGPONG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PINGPONG.setForeground(new java.awt.Color(102, 102, 0));
        PINGPONG.setText("PING PONG");
        PINGPONG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PINGPONGActionPerformed(evt);
            }
        });

        HILLYGROUND.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HILLYGROUND.setForeground(new java.awt.Color(102, 102, 0));
        HILLYGROUND.setText("HILLY GROUND");
        HILLYGROUND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HILLYGROUNDActionPerformed(evt);
            }
        });

        BOOKFACILITYBACKBUTTON.setText("BACK");
        BOOKFACILITYBACKBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOOKFACILITYBACKBUTTONActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(102, 204, 0));
        jLabel4.setText("INSTRUCTOR IS AVAILABLE");

        jLabel9.setForeground(new java.awt.Color(102, 255, 0));
        jLabel9.setText("INSTRUCTOR IS AVAILABLE");

        jLabel11.setForeground(new java.awt.Color(102, 204, 0));
        jLabel11.setText("INSTRUCTOR IS AVAILABLE");

        jLabel12.setForeground(new java.awt.Color(51, 204, 0));
        jLabel12.setText("INSTRUCTOR IS AVAILABLE");

        javax.swing.GroupLayout BOOKFACILITYLayout = new javax.swing.GroupLayout(BOOKFACILITY);
        BOOKFACILITY.setLayout(BOOKFACILITYLayout);
        BOOKFACILITYLayout.setHorizontalGroup(
            BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BOOKFACILITYLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BOOKFACILITYLayout.createSequentialGroup()
                        .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BOOKFACILITYBACKBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                                    .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                                            .addComponent(HANDBALL, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(FITNESS, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BOOKFACILITYLayout.createSequentialGroup()
                                            .addComponent(SWIMMING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(HILLYGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PINGPONG, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(GOLF, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(VOLLEYBALL, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jLabel11)))))
                            .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                                .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TENNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel9))
                                    .addComponent(BADMINTON, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BOOKFACILITYLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
        );
        BOOKFACILITYLayout.setVerticalGroup(
            BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BOOKFACILITYLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PINGPONG, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BADMINTON, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TENNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HANDBALL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GOLF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FITNESS, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(BOOKFACILITYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HILLYGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VOLLEYBALL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SWIMMING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel12)
                .addGap(1, 1, 1)
                .addComponent(BOOKFACILITYBACKBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(BOOKFACILITY, "card4");

        jLabel13.setFont(new java.awt.Font("Aparajita", 2, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 0));
        jLabel13.setText("YOU WISH TO HAVE AN INSTRUCTOR? ");

        INSTRUCTORYESBUTTON.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        INSTRUCTORYESBUTTON.setForeground(new java.awt.Color(255, 0, 0));
        INSTRUCTORYESBUTTON.setText("YES");

        INSTRUCTORNOBUTTON.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        INSTRUCTORNOBUTTON.setForeground(new java.awt.Color(255, 0, 0));
        INSTRUCTORNOBUTTON.setText("NO");

        javax.swing.GroupLayout YOUWANTINSTRUCTORLayout = new javax.swing.GroupLayout(YOUWANTINSTRUCTOR);
        YOUWANTINSTRUCTOR.setLayout(YOUWANTINSTRUCTORLayout);
        YOUWANTINSTRUCTORLayout.setHorizontalGroup(
            YOUWANTINSTRUCTORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, YOUWANTINSTRUCTORLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(YOUWANTINSTRUCTORLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(INSTRUCTORYESBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(INSTRUCTORNOBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        YOUWANTINSTRUCTORLayout.setVerticalGroup(
            YOUWANTINSTRUCTORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YOUWANTINSTRUCTORLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(YOUWANTINSTRUCTORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INSTRUCTORYESBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(INSTRUCTORNOBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        getContentPane().add(YOUWANTINSTRUCTOR, "card5");

        jLabel14.setFont(new java.awt.Font("Aparajita", 2, 36)); // NOI18N
        jLabel14.setText("PICK DATE AND TIME");

        SHOWTIMEDATECOMBOBOX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SHOWTIMEDATELIST.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(SHOWTIMEDATELIST);

        SHOWTIMEDATEBOOKBUTTON.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SHOWTIMEDATEBOOKBUTTON.setForeground(new java.awt.Color(51, 255, 0));
        SHOWTIMEDATEBOOKBUTTON.setText("BOOK");

        javax.swing.GroupLayout SHOWTIMEANDDATELayout = new javax.swing.GroupLayout(SHOWTIMEANDDATE);
        SHOWTIMEANDDATE.setLayout(SHOWTIMEANDDATELayout);
        SHOWTIMEANDDATELayout.setHorizontalGroup(
            SHOWTIMEANDDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWTIMEANDDATELayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(SHOWTIMEANDDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SHOWTIMEANDDATELayout.createSequentialGroup()
                        .addComponent(SHOWTIMEDATECOMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(SHOWTIMEDATEBOOKBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        SHOWTIMEANDDATELayout.setVerticalGroup(
            SHOWTIMEANDDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHOWTIMEANDDATELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SHOWTIMEANDDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SHOWTIMEDATEBOOKBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SHOWTIMEANDDATELayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(SHOWTIMEANDDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SHOWTIMEDATECOMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(SHOWTIMEANDDATE, "card6");

        jLabel15.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 0));
        jLabel15.setText("YOU ARE NOW BOOKED IN");

        jLabel16.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 0));
        jLabel16.setText("THANK YOU, HAVE A GOOD DAY");

        THANKYOUBUTTON.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        THANKYOUBUTTON.setForeground(new java.awt.Color(51, 255, 0));
        THANKYOUBUTTON.setText("THANK YOU");

        javax.swing.GroupLayout YOUARENOWBOOKEDINLayout = new javax.swing.GroupLayout(YOUARENOWBOOKEDIN);
        YOUARENOWBOOKEDIN.setLayout(YOUARENOWBOOKEDINLayout);
        YOUARENOWBOOKEDINLayout.setHorizontalGroup(
            YOUARENOWBOOKEDINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YOUARENOWBOOKEDINLayout.createSequentialGroup()
                .addGroup(YOUARENOWBOOKEDINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(YOUARENOWBOOKEDINLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(YOUARENOWBOOKEDINLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(THANKYOUBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(YOUARENOWBOOKEDINLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        YOUARENOWBOOKEDINLayout.setVerticalGroup(
            YOUARENOWBOOKEDINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YOUARENOWBOOKEDINLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(THANKYOUBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(YOUARENOWBOOKEDIN, "card7");

        DELETEBOOKINGLIST.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(DELETEBOOKINGLIST);

        jLabel17.setFont(new java.awt.Font("Aparajita", 2, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 0));
        jLabel17.setText("PICK YOUR BOOKING TO DELETE");

        DELETEBOOKINGBACKBUTTON.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        DELETEBOOKINGBACKBUTTON.setForeground(new java.awt.Color(51, 255, 0));
        DELETEBOOKINGBACKBUTTON.setText("BACK");

        DELETEBOOKINGBUTTON.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        DELETEBOOKINGBUTTON.setForeground(new java.awt.Color(255, 51, 51));
        DELETEBOOKINGBUTTON.setText("DELETE");

        javax.swing.GroupLayout DELETEBOOKINGLayout = new javax.swing.GroupLayout(DELETEBOOKING);
        DELETEBOOKING.setLayout(DELETEBOOKINGLayout);
        DELETEBOOKINGLayout.setHorizontalGroup(
            DELETEBOOKINGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DELETEBOOKINGLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(DELETEBOOKINGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DELETEBOOKINGBACKBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DELETEBOOKINGBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DELETEBOOKINGLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        DELETEBOOKINGLayout.setVerticalGroup(
            DELETEBOOKINGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DELETEBOOKINGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(DELETEBOOKINGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DELETEBOOKINGLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DELETEBOOKINGLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DELETEBOOKINGBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DELETEBOOKINGBACKBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );

        getContentPane().add(DELETEBOOKING, "card8");

        jLabel18.setFont(new java.awt.Font("Aparajita", 2, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 0));
        jLabel18.setText("YOU HAVE DELETED YOUR BOOKING");

        jLabel19.setFont(new java.awt.Font("Aparajita", 2, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 0));
        jLabel19.setText("HAVE A GOOD DAY");

        YOUHAVEDELETEDBACKBUTTON.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        YOUHAVEDELETEDBACKBUTTON.setForeground(new java.awt.Color(51, 255, 51));
        YOUHAVEDELETEDBACKBUTTON.setText("BACK");
        YOUHAVEDELETEDBACKBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YOUHAVEDELETEDBACKBUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout YOUHAVEDELETEDLayout = new javax.swing.GroupLayout(YOUHAVEDELETED);
        YOUHAVEDELETED.setLayout(YOUHAVEDELETEDLayout);
        YOUHAVEDELETEDLayout.setHorizontalGroup(
            YOUHAVEDELETEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, YOUHAVEDELETEDLayout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, YOUHAVEDELETEDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(YOUHAVEDELETEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, YOUHAVEDELETEDLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, YOUHAVEDELETEDLayout.createSequentialGroup()
                        .addComponent(YOUHAVEDELETEDBACKBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))))
        );
        YOUHAVEDELETEDLayout.setVerticalGroup(
            YOUHAVEDELETEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YOUHAVEDELETEDLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(YOUHAVEDELETEDBACKBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        getContentPane().add(YOUHAVEDELETED, "card9");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUESTUSERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUESTUSERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUESTUSERNAMEActionPerformed

    private void BOOKFACILITYBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOKFACILITYBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOOKFACILITYBUTTONActionPerformed

    private void CHECKBOOKINGBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECKBOOKINGBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHECKBOOKINGBUTTONActionPerformed

    private void LOGOUTBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGOUTBUTTONActionPerformed

    private void BOOKFACILITYBACKBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOKFACILITYBACKBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOOKFACILITYBACKBUTTONActionPerformed

    private void HILLYGROUNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HILLYGROUNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HILLYGROUNDActionPerformed

    private void PINGPONGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PINGPONGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PINGPONGActionPerformed

    private void FITNESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FITNESSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FITNESSActionPerformed

    private void SWIMMINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SWIMMINGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SWIMMINGActionPerformed

    private void HANDBALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HANDBALLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HANDBALLActionPerformed

    private void GOLFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOLFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GOLFActionPerformed

    private void TENNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TENNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TENNISActionPerformed

    private void BADMINTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BADMINTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BADMINTONActionPerformed

    private void VOLLEYBALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLLEYBALLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VOLLEYBALLActionPerformed

    private void YOUHAVEDELETEDBACKBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YOUHAVEDELETEDBACKBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YOUHAVEDELETEDBACKBUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BADMINTON;
    private javax.swing.JPanel BOOKFACILITY;
    private javax.swing.JButton BOOKFACILITYBACKBUTTON;
    private javax.swing.JButton BOOKFACILITYBUTTON;
    private javax.swing.JButton CHECKBOOKINGBUTTON;
    private javax.swing.JPanel DELETEBOOKING;
    private javax.swing.JButton DELETEBOOKINGBACKBUTTON;
    private javax.swing.JButton DELETEBOOKINGBUTTON;
    private javax.swing.JList DELETEBOOKINGLIST;
    private javax.swing.JButton FITNESS;
    private javax.swing.JButton GOLF;
    private javax.swing.JLabel GUESTFEEDBACK;
    private javax.swing.JButton GUESTLOGIN;
    private javax.swing.JTextField GUESTPASSWORD;
    private javax.swing.JTextField GUESTUSERNAME;
    private javax.swing.JButton HANDBALL;
    private javax.swing.JButton HILLYGROUND;
    private javax.swing.JButton INSTRUCTORNOBUTTON;
    private javax.swing.JButton INSTRUCTORYESBUTTON;
    private javax.swing.JPanel LOGIN;
    private javax.swing.JButton LOGOUTBUTTON;
    private javax.swing.JButton PINGPONG;
    private javax.swing.JPanel SHOWTIMEANDDATE;
    private javax.swing.JButton SHOWTIMEDATEBOOKBUTTON;
    private javax.swing.JComboBox SHOWTIMEDATECOMBOBOX;
    private javax.swing.JList SHOWTIMEDATELIST;
    private javax.swing.JButton SWIMMING;
    private javax.swing.JButton TENNIS;
    private javax.swing.JButton THANKYOUBUTTON;
    private javax.swing.JButton VOLLEYBALL;
    private javax.swing.JPanel WELCOME;
    private javax.swing.JPanel YOUARENOWBOOKEDIN;
    private javax.swing.JPanel YOUHAVEDELETED;
    private javax.swing.JButton YOUHAVEDELETEDBACKBUTTON;
    private javax.swing.JPanel YOUWANTINSTRUCTOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
